#!/bin/bash

echo ""
echo "Update Packages"
apt update
apt install curl jq -y

echo ""
echo "Installing K3S Kubernetes"
cp /certificates/fortidemoCA.crt /usr/local/share/ca-certificates/ 
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san 10.1.1.200" sh -

echo ""
echo "Get Kubeconfig and Set Permissions"
chmod a+r /etc/rancher/k3s/k3s.yaml
mkdir -p /home/fortinet/.kube
cat /etc/rancher/k3s/k3s.yaml | sed 's/127.0.0.1/10.1.1.200/g' > /home/fortinet/.kube/config
chown -R fortinet:fortinet /home/fortinet

echo ""
echo "# Install mettallb (DeepSeek)"
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
sleep 30
kubectl wait --namespace metallb-system --for=condition=ready pod --selector=app=metallb --timeout=90s

echo "# Configure Metallb for Subnet Range: 10.1.1.230-10.1.1.250"
cat <<EOF | kubectl apply -f -
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dhcp-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.1.1.220-10.1.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - dhcp-pool
EOF

sleep 5

echo "# Show Ingress IP Address"
kubectl get svc -n kube-system traefik

# Changw Ownership and Permissions
chown -R fortinet:fortinet /home/fortinet/cert /home/fortinet/fortidemoCA.crt
