#!/bin/bash

echo "# Install Packages"
apt update
apt install mysql-client net-tools curl -y

# Set MySQL root password
MYSQL_ROOT_PASSWORD="fortinet"
ADMIN_PASSWORD="fortinet"

# Install MySQL
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server

# Configure MySQL
sed -i 's/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf

# Set root password
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${MYSQL_ROOT_PASSWORD}';"

# Create admin user
mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF
CREATE USER 'admin'@'%' IDENTIFIED BY '${ADMIN_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF

# Configure firewall
# ufw allow 3306/tcp
# ufw reload

# Restart MySQL
systemctl restart mysql

echo "MySQL installation and configuration complete"

