#!/bin/bash
#===============================================================================
# SCRIPT NAME:    modules/debcli_postinst
# DESCRIPTION:    Additions
# AUTHOR:         Sacha Dubois, Fortinet
# CREATED:        2025-03-14
# VERSION:        1.0
#===============================================================================
# CHANGE LOG: 
# 2025-03-15 sdubois Initial version
# 2025-05-07 sdubois Added dependancy file
#===============================================================================

export INSTALL_CHROME=0
export INSTALL_MARKTEXT=0
export INSTALL_ANSIBLE=0
export KUBECTL_CLIENT=0
export DBEAVER_CE=0
export WIRESHARK=0

echo "############################### Start fortipoc/postinst ###############################"

echo "=> Set permision and ownership for /home/fortinet"
[ -d /home/fortinet ] && chown -R fortinet:fortinet /home/fortinet 
chown root:root / /fortipoc /home

echo "=> Update Installed Packages"
apt update -qq > /dev/null 2>&1; ret=$?
[ $ret -ne 0 ] && echo "   ▪ Package update failed, check internet connection" && exit 1

echo "=> Installing Additional Packages"
apt install lynx -y -qq  > /dev/null 2>&1
#apt install libnss3-tools mysql-client curl software-properties-common bat python3-pip net-tools jq traceroute wireshark -y -qq  > /dev/null 2>&1
pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org Faker  > /dev/null 2>&1

for pkg in libnss3-tools mysql-client curl software-properties-common bat python3 python3-pip net-tools jq traceroute wireshark; do
  dpkg -s "$pkg" >/dev/null 2>&1; ret=$?
  if [ $ret -ne 0 ]; then
    apt install -y -qq "$pkg" > /tmp/${pkg}.log 2>&1; ret=$?
    if [ $ret -ne 0 ]; then
      echo "   ▪ Package installation of $pkg failed"
      echo "---------------------------------------------------------------------------------------"
      cat /tmp/${pkg}.log
      echo "---------------------------------------------------------------------------------------"
    else
      echo "   ▪ Package installation of $pkg compleded"
    fi
  else
    echo "   ▪ Package $pkg is already installed"
  fi
done

#################################################################################################
######################################## MYSQL_WORKBENCH ########################################
#################################################################################################
if [ $DBEAVER_CE -eq 1 ]; then
  echo "=> Installing dbeaver-ce"
  if ! snap list dbeaver-ce >/dev/null 2>&1; then
    snap install dbeaver-ce > /tmp/dbeaver-ce.log 2>&1; ret=$?
    if [ $ret -ne 0 ]; then
      echo "   ▪ Installation of dbeaver-ce failed"
      echo "---------------------------------------------------------------------------------------"
      cat /tmp/dbeaver-ce.log
      echo "---------------------------------------------------------------------------------------"
    else
      echo "   ▪ Installation of dbeaver-ce completed"
    fi
  else
    echo "   ▪ dbeaver-ce is already installed"
  fi
fi

#################################################################################################
##################################### ANSIBLE INSTALLATION ######################################
#################################################################################################
if [ $INSTALL_ANSIBLE -eq 2 ]; then
  echo "=> Install Ansible"

  if ! grep -h "^deb .*\bppa.launchpad.net/ansible/ansible\b" /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null; then
    apt-add-repository --yes --update ppa:ansible/ansible > /tmp/ansible_repo.log 2>&1; ret=$?
    if [ $ret -ne 0 ]; then
      echo "   ▪ Adding repository ppa:ansible/ansible failed"
      echo "---------------------------------------------------------------------------------------"
      cat /tmp/ansible_repo.log
      echo "---------------------------------------------------------------------------------------"
    else
      echo "   ▪ Adding repository ppa:ansible/ansible completed"
    fi
  else
    echo "   ▪ Repository ppa:ansible/ansible completed already configured"
  fi

  apt update -qq > /dev/null 2>&1; ret=$?
  if [ $ret -ne 0 ]; then
     echo "   ▪ Package update failed, check internet connection"
  else
     echo "   ▪ Package update completed"
  fi

  for pkg in ansible; do
    dpkg -s "$pkg" &>/dev/null; ret=$?
    if [ $ret -ne 0 ]; then
      apt install -y -qq "$pkg" > /tmp/${pkg}.log 2>&1; ret=$?
      if [ $ret -ne 0 ]; then
        echo "   ▪ Package installation of $pkg failed"
        echo "---------------------------------------------------------------------------------------"
        cat /tmp/${pkg}.log
        echo "---------------------------------------------------------------------------------------"
      else
        echo "   ▪ Package installation of $pkg compleded"
      fi
    else
      echo "   ▪ Package $pkg is already installed"
    fi
  done

  echo "=> Install Ansible Galaxy Fortinet Collection"
  if ! ansible-galaxy collection list | grep -q '^fortinet.fortiadc'; then
    ansible-galaxy collection install fortinet.fortiadc  > /tmp/galaxy.log 2>&1; ret=$?
    if [ $ret -ne 0 ]; then
      echo "   ▪ Installation of Ansible Galaxy Collection of fortinet.fortiadc failed"
      echo "---------------------------------------------------------------------------------------"
      cat /tmp/galaxy.log
      echo "---------------------------------------------------------------------------------------"
    else
      echo "   ▪ Installation of Ansible Galaxy Collection of fortinet.fortiadc Completed"
    fi
  else
    echo "   ▪ Ansible Galaxy Collection of fortinet.fortiadc already installed"
  fi
fi

#################################################################################################
#################################### MARKTEXT INSTALLATION ######################################
#################################################################################################
if [ $INSTALL_MARKTEXT -eq 1 ]; then
  echo "=> Install MarkText"
  if ! snap list marktext >/dev/null 2>&1; then
    snap install marktext > /tmp/marktext.log 2>&1; ret=$?
    if [ $ret -ne 0 ]; then
      echo "   ▪ Installation of dbeaver-ce failed"
      echo "---------------------------------------------------------------------------------------"
      cat /tmp/marktext.log
      echo "---------------------------------------------------------------------------------------"
    else
      echo "   ▪ Installation of marktext completed"
    fi
  else
    echo "   ▪ marktext is already installed"
  fi
fi

#################################################################################################
##################################### KUBECTL INSTALLATION ######################################
#################################################################################################
if [ $KUBECTL_CLIENT -eq 1 ]; then
  echo "=> Install kubectl"
  pkg="kubectl"
  if ! snap list ${pkg} >/dev/null 2>&1; then
    snap install $pkg --classic > /tmp/${pkg}.log 2>&1; ret=$?
    if [ $ret -ne 0 ]; then
      echo "   ▪ Installation of dbeaver-ce failed"
      echo "---------------------------------------------------------------------------------------"
      cat /tmp/${pkg}.log
      echo "---------------------------------------------------------------------------------------"
    else
      echo "   ▪ Installation of ${pkg} completed"
    fi
  else
    echo "   ▪ marktext is ${pkg} installed"
  fi

  echo "   ▪ Adding debk3s (10.1.1.200) to /etc/hosts"
  echo "10.1.1.200 debk3s" >> /etc/hosts

  [ -d /home/fortinet/.ssh ] && chown -R fortinet:fortinet /home/fortinet/.ssh
  [ ! -d /home/fortinet/.kube ] && mkdir -p /home/fortinet/.kube && chown -R fortinet:fortinet /home/fortinet/.kube
  for n in 1 2 3; do
    su - fortinet -c "scp fortinet@debk3s:/home/fortinet/.kube/config /home/fortinet/.kube/config" > /tmp/scplog 2>&1; ret=$?
    [ $ret -eq 0 ] && break || sleep 30
  done

  if [ $ret -ne 0 ]; then
    echo "   ▪ Copy the Kubeconfig (/home/fortinet/.kube/config) from fortinet@debk3s failed"
    echo "---------------------------------------------------------------------------------------"
    cat /tmp/scplog
    echo "---------------------------------------------------------------------------------------"
  else
    echo "   ▪ Copy the Kubeconfig (/home/fortinet/.kube/config) from fortinet@debk3s compleded"
  fi
fi

echo "=> Installing Phyton Libraries" 
for pkg in rich; do
  if ! pip3 show $pkg >/dev/null 2>&1; then
    pip3 install "$pkg" > /tmp/${pkg}.log 2>&1; ret=$?
    if [ $ret -ne 0 ]; then
      echo "   ▪ Installation of Phyton Library $pkg failed"
      echo "---------------------------------------------------------------------------------------"
      cat /tmp/${pkg}.log
      echo "---------------------------------------------------------------------------------------"
    else
      echo "   ▪ Installation of Phyton Library $pkg completed"
    fi
  else
    echo "   ▪ Phyton Library $pkg is already installed"
  fi
done

echo "=> Create Log Directory (/var/log/fortinet)"
mkdir -p /var/log/fortinet && chown fortinet:fortinet /var/log/fortinet

#echo "=> Change Script Permission"
#chown fortinet:fortinet /home/fortinet/bin/res
#chown fortinet:fortinet /home/fortinet/bin/xkb
#chmod a+x /home/fortinet/bin/res /home/fortinet/bin/xkb

#################################################################################################
################################### GOOGLE CROME INSTALLATION ###################################
#################################################################################################
if [ $INSTALL_CHROME -eq 1 ]; then 
  # icon -> /usr/bin/google-chrome-stable -> /opt/google/chrome/google-chrome -> 
  # Auto -> /usr/bin/google-chrome

  rm -rf /usr/bin/google-chrome /usr/bin/google-chrome-stable
  [ -f /google/google-chrome-stable ] && cp /google/google-chrome-stable /usr/bin/google-chrome-stable && chmod a+x /usr/bin/google-chrome-stable
  [ -f /google/google-chrome ] && cp /google/google-chrome /usr/bin/google-chrome && chmod a+x /usr/bin/google-chrome

  # Enable Run Script
  xdg-mime default runscript.desktop x-scheme-handler/runscript
  #su - fortinet -c "xdg-mime default runscript.desktop x-scheme-handler/runscript"
fi

if [ $INSTALL_CHROME -eq 2 ]; then 
  echo "=> Install Chrome Browser"
  dpkg -s "google-chrome-stable" >/dev/null 2>&1; ret=$?
  if [ $ret -ne 0 ]; then
    wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > /tmp/google-chrome-stable.log 2>&1; ret=$?
    if [ $ret -ne 0 ]; then
      echo "   ▪ Downloading Debian Package dependancy (google-chrome-stable_current_amd64.deb) from GitHub failed"
      echo "---------------------------------------------------------------------------------------"
      cat /tmp/google-chrome-stable.log
      echo "---------------------------------------------------------------------------------------"
    else
      echo "   ▪ Downloading Debian Package dependancy (google-chrome-stable_current_amd64.deb) from GitHub completed"
    fi
  
    dpkg -i /google-chrome-stable_current_amd64.deb > /dev/null 2>&1
    apt-get install -f > /dev/null 2>&1
    apt install -qq /google-chrome-stable_current_amd64.deb > /tmp/chrome.log 2>&1; ret=$?
    if [ $ret -ne 0 ]; then
      echo "   ▪ Package installation of google-chrome-stable_current_amd64 failed"
      echo "---------------------------------------------------------------------------------------"
      cat /tmp/chrome.log
      echo "---------------------------------------------------------------------------------------"
    else
      echo "   ▪ Package installation of google-chrome-stable_current_amd64 compleded"
    fi
  else
    echo "   ▪ Package google-chrome-stable is already installed"
  fi
fi

#################################################################################################
################################## SETUP DESKTOP AND KEYBOARD ###################################
#################################################################################################

echo "=> Configure KDE Desktop"
echo "   ▪ Disable scrrnlock and screensaver"
kwriteconfig5 --file kscreenlockerrc --group Daemon --key Autolock false
kwriteconfig5 --file kscreenlockerrc --group Daemon --key LockOnResume false

echo "   ▪ Restarting XDDM"
systemctl restart sddm > /dev/null 2>&1 && sleep 60

echo "=> Create NSS DB"
[ ! -d /home/fortinet/.pki/nssdb ] && mkdir -p /home/fortinet/.pki/nssdb
echo "   ▪ Create NSSDB Password File"
echo fortinet > /home/fortinet/.pki/pwfile

[ ! -f /home/fortinet/.pki/nssdb/cert9.db ] && certutil -N -d sql:/home/fortinet/.pki/nssdb -f /home/fortinet/.pki/pwfile
echo "   ▪ Register Fortinet. Globex, Apex and ACME CA Certificate"
echo "     ---------------------------------------------------------------------------------------"
certutil -d sql:/home/fortinet/.pki/nssdb -A -t "C,," -n "Fortidemo CA" -i  /home/fortinet/cert/fortidemo/ca.crt -f /home/fortinet/.pki/pwfile
certutil -d sql:/home/fortinet/.pki/nssdb -A -t "C,," -n "Globex CA" -i  /home/fortinet/cert/globex/ca.crt -f /home/fortinet/.pki/pwfile
certutil -d sql:/home/fortinet/.pki/nssdb -A -t "C,," -n "APEX CA" -i  /home/fortinet/cert/apex/ca.crt -f /home/fortinet/.pki/pwfile
certutil -d sql:/home/fortinet/.pki/nssdb -A -t "C,," -n "ACME CA" -i  /home/fortinet/cert/acme/ca.crt -f /home/fortinet/.pki/pwfile
certutil -L -d sql:/home/fortinet/.pki/nssdb | sed -e 's/^/     /g' -e '/^    $/d' 
echo "     ---------------------------------------------------------------------------------------"

echo "   ▪ Create a Fortidemo Certificate Bundle (/etc/ssl/certs/fortidemo-bundle.crt)"
cat /home/fortinet/cert/fortidemo/ca.crt /home/fortinet/cert/globex/ca.crt /home/fortinet/cert/apex/ca.crt /home/fortinet/cert/acme/ca.crt > /etc/ssl/certs/fortidemo-bundle.crt

[ -d /home/fortinet/.pki ] && chown -R fortinet:fortinet /home/fortinet/.pki 
[ -f /home/fortinet/certutil.log ] && chown -R fortinet:fortinet /home/fortinet/certutil.log

#echo "   ▪ Set Screen Resolution (again)"
#su - fortinet -c "/home/fortinet/bin/res"

echo "############################### Start fortipoc/postinst ###############################"

