#!/bin/bash
#===============================================================================
# SCRIPT NAME:    modules/debk3s_flannel_SNAT_postinst
# DESCRIPTION:    Additions
# AUTHOR:         Sacha Dubois, Fortinet
# CREATED:        2025-03-14
# VERSION:        1.0
#===============================================================================
# CHANGE LOG:
# 2025-03-15 sdubois Initial version
# 2025-05-07 sdubois Added dependancy file
#===============================================================================

echo "############################### Start fortipoc/postinst ###############################"

echo "=> Update Installed Packages"
apt update -qq > /dev/null 2>&1; ret=$?
[ $ret -ne 0 ] && echo "   ▪ Package update failed, check internet connection" && exit 1

echo "=> Installing Additional Packages"
for pkg in curl jq traceroute net-tools; do
  apt install -y -qq "$pkg" > /tmp/${pkg}.log 2>&1; ret=$?  
  if [ $ret -ne 0 ]; then
    echo "   ▪ Package installation of $pkg failed"
    echo "---------------------------------------------------------------------------------------"
    cat /tmp/${pkg}.log
    echo "---------------------------------------------------------------------------------------"
  else
    echo "   ▪ Package installation of $pkg compleded"
  fi 
done

echo "=> Installing K3S Kubernetes"
cp /certificates/fortidemoCA.crt /usr/local/share/ca-certificates/ 
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--tls-san 10.1.1.200" sh -

echo "   ▪ Get Kubeconfig and Set Permissions"
chmod a+r /etc/rancher/k3s/k3s.yaml
mkdir -p /home/fortinet/.kube
cat /etc/rancher/k3s/k3s.yaml | sed 's/127.0.0.1/10.1.1.200/g' > /home/fortinet/.kube/config
chown -R fortinet:fortinet /home/fortinet

echo "   ▪ Install mettallb (DeepSeek)"
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
sleep 30
kubectl wait --namespace metallb-system --for=condition=ready pod --selector=app=metallb --timeout=90s

echo "   ▪ Configure Metallb for Subnet Range: 10.1.1.230-10.1.1.250"
cat <<EOF | kubectl apply -f -
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dhcp-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.1.1.220-10.1.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - dhcp-pool
EOF

sleep 5

echo "=> Password less SuDo"
chown root:root /etc/sudoers.d /etc/sudoers.d/fortinet

echo "=> Show Ingress IP Address"
kubectl get svc -n kube-system traefik

# Changw Ownership and Permissions
chown -R fortinet:fortinet /home/fortinet/cert /home/fortinet/fortidemoCA.crt

echo "############################### End fortipoc/postinst ###############################"
