#!/bin/bash
#===============================================================================
# SCRIPT NAME:    modules/debk3s_osscalico_noSNAT_postinst
# DESCRIPTION:    Additions
# AUTHOR:         Sacha Dubois, Fortinet
# CREATED:        2025-03-14
# VERSION:        1.0
#===============================================================================
# CHANGE LOG:
# 2025-03-15 sdubois Initial version
# 2025-05-07 sdubois Added dependancy file
# 2025-09-04 sdubois Added Kubernetes audit logging
# 2025-09-28 sdubois restric kubernetes to INSTALL_K3S_VERSION="v1.32.9+k3s1" 
#===============================================================================

export COPY_KUBCONFIG_DEBCLI=0
export COPY_KUBCONFIG_DEBADM=0
export APP_ECHOSERVER_INGRESS=0
export APP_EDB_INGRESS=0
export APP_GLOBEX_INGRESS=0
export APP_APEX_INGRESS=0
export APP_ACME_INGRESS=0
export APP_TOOLBOX_INGRESS=0
export PROXY_DEFAULT_ROUTER=0

echo "############# Start fortipoc/postinst (debk3s_osscalico_noSNAT_postinst) ##############"

echo "=> Update Installed Packages"
apt update -qq > /dev/null 2>&1; ret=$?
[ $ret -ne 0 ] && echo "   ▪ Package update failed, check internet connection" && exit 1

echo "=> Installing Additional Packages"
apt install curl net-tools traceroute jq -y -qq  > /dev/null 2>&1

#for pkg in mysql-client net-tools curl traceroute; do
#  dpkg -s "$pkg" &>/dev/null; ret=$?  
#  if [ $ret -ne 0 ]; then
#    apt install -y -qq "$pkg" > /tmp/${pkg}.log 2>&1; ret=$?
#    if [ $ret -ne 0 ]; then
#      echo "   ▪ Package installation of $pkg failed"
#      echo "---------------------------------------------------------------------------------------"
#      cat /tmp/${pkg}.log
#      echo "---------------------------------------------------------------------------------------"
#    else
#      echo "   ▪ Package installation of $pkg compleded"
#    fi
#  else
#    echo "   ▪ Package $pkg is already installed"
#  fi
#done

echo "=> Installing Helm"
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 2>/dev/null | bash > /dev/null 2>&1

#-------------------------------------------------------------------------------
# Enable Kubernetes Audit Logging
# Audit Logs: /var/lib/rancher/k3s/server/logs/audit.log
#-------------------------------------------------------------------------------
echo "=> Enabling Kubernetes Audit Logging"

# Create audit policy file
mkdir -p /etc/rancher/k3s
cat <<EOF >/etc/rancher/k3s/audit-policy.yaml
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
EOF

#-------------------------------------------------------------------------------
# Install K3S with Calico
#-------------------------------------------------------------------------------
echo "=> Installing K3S Kubernetes (debk3s_osscalico_noSNAT_postinst)"
# https://docs.tigera.io/calico/latest/getting-started/kubernetes/k3s/quickstart
curl -sfL https://get.k3s.io | \
  INSTALL_K3S_VERSION="v1.32.9+k3s1" \
  K3S_KUBECONFIG_MODE="644" \
  INSTALL_K3S_EXEC="--tls-san 10.1.1.200 \
    --flannel-backend=none \
    --cluster-cidr=192.168.0.0/16 \
    --disable-network-policy \
    --disable=traefik \
    --kube-apiserver-arg=audit-policy-file=/etc/rancher/k3s/audit-policy.yaml \
    --kube-apiserver-arg=audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log \
    --kube-apiserver-arg=audit-log-maxage=30 \
    --kube-apiserver-arg=audit-log-maxbackup=10 \
    --kube-apiserver-arg=audit-log-maxsize=100" \
  sh -

#echo "=> Installing K3S Kubernetes (debk3s_osscalico_noSNAT_postinst)"
# https://docs.tigera.io/calico/latest/getting-started/kubernetes/k3s/quickstart
#curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--tls-san 10.1.1.200 --flannel-backend=none --cluster-cidr=192.168.0.0/16 --disable-network-policy --disable=traefik" sh -

sleep 10

echo "# Install Calico and patch 'natOutgoing: true' to 'natOutgoing: false' in IP-Pool: default-ipv4-ippoolit"
kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.0/manifests/calico.yaml
kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=500s

kubectl patch ippool default-ipv4-ippool --type merge -p '{"spec":{"natOutgoing":false}}'
kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=500s
echo "#####################################################################################"
kubectl get ippool default-ipv4-ippool -o yaml
echo "#####################################################################################"

echo "# Setup Kubeconfig"
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

echo "   ▪ Install mettallb"
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
sleep 30
kubectl wait --namespace metallb-system --for=condition=ready pod --selector=app=metallb --timeout=90s

echo "   ▪ Configure Metallb for Subnet Range: 10.1.1.230-10.1.1.250"
cat <<EOF | kubectl apply -f -
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dhcp-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.1.1.220-10.1.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - dhcp-pool
EOF

echo "   ▪ Install Traefik"
helm repo add traefik https://traefik.github.io/charts
helm repo update
helm install traefik traefik/traefik \
  --namespace kube-system \
  --set service.type=LoadBalancer

kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

echo "   ▪ Get Kubeconfig and Set Permissions"
chmod a+r /etc/rancher/k3s/k3s.yaml
mkdir -p /home/fortinet/.kube
cat /etc/rancher/k3s/k3s.yaml | sed 's/127.0.0.1/10.1.1.200/g' > /home/fortinet/.kube/config
chown -R fortinet:fortinet /home/fortinet

sleep 5

echo "=> Password less SuDo"
chown root:root /etc/sudoers.d /etc/sudoers.d/fortinet

echo "=> Kubernetes Configuration"
ipa=$(kubectl get svc -n kube-system traefik -o json | jq -r '.status.loadBalancer.ingress[].ip')
echo "   ▪ IP Address of the Ingress Controller (traefik): $ipa"

if [ "$PROXY_DEFAULT_ROUTER" -eq 1 ]; then
  echo "   ▪ Change default router to 10.1.1.1 on interface ens3"
  ip route del default > /dev/null 2>&1
  ip route add default via 10.1.1.1 dev ens3 > /dev/null 2>&1
fi

echo "=> Install FortiADC Ingress"
echo "   ▪ Add Helm repo https://fortinet.github.io/fortiadc-ingress"
helm repo add fortiadc-ingress-controller https://fortinet.github.io/fortiadc-ingress/ > /dev/null 2>&1
helm repo update > /dev/null 2>&1

echo "   ▪ Install FortiADC Ingress controller in namespace (fortiadc-ingress)"
helm install adc-ingress --namespace fortiadc-ingress \
--set controller.ingressClassResource.default=false \
--create-namespace --wait fortiadc-ingress-controller/fadc-k8s-ctrl > /dev/null 2>&1

echo "   ▪ Create Secret with FortiADC Access Parameters"
kubectl create secret generic fad-login -n fortiadc-ingress \
--from-literal=username=admin --from-literal=password='F0rt!net' > /dev/null 2>&1

sleep 20

if [ $APP_ECHOSERVER_INGRESS -eq 1 ]; then 
  su - fortinet -c "/home/fortinet/bin/deploy-echoserver-ingress-traefik.sh > /dev/null 2>&1"
  su - fortinet -c "/home/fortinet/bin/deploy-echoserver-ingress-fadc-nodeport.sh > /dev/null 2>&1"
  echo "   ▪ Application (echoserver) deployed"
fi

[ $APP_EDB_INGRESS -eq 1 ] && su - fortinet -c "/home/fortinet/bin/deploy-edb-ingress.sh > /dev/null 2>&1" && echo "   ▪ Application (edb) deployed"
[ $APP_GLOBEX_INGRESS -eq 1 ] && su - fortinet -c "/home/fortinet/bin/deploy-globex-ingress.sh > /dev/null 2>&1" && echo "   ▪ Application (globex) deployed"
[ $APP_APEX_INGRESS -eq 1 ] && su - fortinet -c "/home/fortinet/bin/deploy-apex-ingress.sh > /dev/null 2>&1" && echo "   ▪ Application (apex) deployed"
[ $APP_ACME_INGRESS -eq 1 ] && su - fortinet -c "/home/fortinet/bin/deploy-acme-ingress.sh > /dev/null 2>&1" && echo "   ▪ Application (acme) deployed"
[ $APP_TOOLBOX_INGRESS -eq 1 ] && su - fortinet -c "/home/fortinet/bin/deploy-toolbox-ingress.sh > /dev/null 2>&1" && echo "   ▪ Application (toolbox) deployed"

echo "=> Changw Ownership and Permissions"
chown -R fortinet:fortinet /home/fortinet/cert /home/fortinet/fortidemoCA.crt

echo "############### End fortipoc/postinst (debk3s_osscalico_noSNAT_postinst) ##############"

