#!/bin/bash

echo ""
echo "Update Packages"
apt update
apt install curl jq traceroute -y

echo "# Installing K3S Kubernetes"
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash > /dev/null 2>&1

#curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--tls-san 10.1.1.200 --flannel-backend=none --cluster-cidr=10.100.0.0/16 --disable-network-policy --disable=traefik" sh -

# https://docs.tigera.io/calico/latest/getting-started/kubernetes/k3s/quickstart
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--tls-san 10.1.1.200 --flannel-backend=none --cluster-cidr=192.168.0.0/16 --disable-network-policy --disable=traefik" sh -
sleep 10

echo "# Install Calico and patch it for natOutgoing: false"
kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/calico.yaml
kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

#kubectl delete ippool default-ipv4-ippool
#cat <<EOF | kubectl apply -f -
#apiVersion: crd.projectcalico.org/v1
#kind: IPPool
#metadata:
#  name: default-ipv4-ippool
#spec:
#  cidr: 10.100.0.0/16
#  natOutgoing: false
#  ipipMode: Never
#  vxlanMode: Never
#  nodeSelector: all()
#EOF

#kubectl patch ippool default-ipv4-ippool --type merge -p '{"spec":{"natOutgoing":false}}'
kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s
echo "#####################################################################################"
kubectl get ippool default-ipv4-ippool -o yaml
echo "#####################################################################################"

echo "# Setup Kubeconfig"
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

echo ""
echo "# Install mettallb (DeepSeek)"
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
sleep 30
kubectl wait --namespace metallb-system --for=condition=ready pod --selector=app=metallb --timeout=90s

echo "# Configure Metallb for Subnet Range: 10.1.1.230-10.1.1.250"
cat <<EOF | kubectl apply -f -
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dhcp-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.1.1.220-10.1.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - dhcp-pool
EOF

echo "# Install Traefik"
helm repo add traefik https://traefik.github.io/charts
helm repo update
helm install traefik traefik/traefik \
  --namespace kube-system \
  --set service.type=LoadBalancer

kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s

echo "Get Kubeconfig and Set Permissions"
chmod a+r /etc/rancher/k3s/k3s.yaml
mkdir -p /home/fortinet/.kube
cat /etc/rancher/k3s/k3s.yaml | sed 's/127.0.0.1/10.1.1.200/g' > /home/fortinet/.kube/config
chown -R fortinet:fortinet /home/fortinet

sleep 5

echo "# Password less SuDo"
chown root:root /etc/sudoers.d /etc/sudoers.d/fortinet

echo "# Show Ingress IP Address"
kubectl get svc -n kube-system traefik

# Changw Ownership and Permissions
chown -R fortinet:fortinet /home/fortinet/cert /home/fortinet/fortidemoCA.crt
